// src/app/layout.tsx

import React from 'react';
import { AuthProvider } from '@/context/AuthContext'; // Adjust the path as necessary
import { Open_Sans } from 'next/font/google';
import "./globals.css";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Housinn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className='w-full'>
      <body className={`${sans.className} w-full`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
